### ISSUE TITLE
log running time?

### ISSUE THREAD

**Issue by gblazex** [mlabonne/llm-autoeval#1]
I love how simply this runs.

it would be useful to log how long the test took to run.

Maybe an optional checkbox on the colab and the code handles it?

**Comment by gblazex** [comment]
also CodeNinja and xDan 7B models fail to run. There is no error logged to gist or anywhere that I can see.
(gist just logs "File not found" for as results of tests)

**Comment by mlabonne** [comment]
Thanks! Yeah I thought about it too, I'll add the runtime very soon.

You can run the debug mode to check the logs. In most cases, the model doesn't have a tokenizer in its repo.

**Comment by mlabonne** [comment]
It's added: https://github.com/mlabonne/llm-autoeval/pull/2
