### ISSUE TITLE
File does not exist% on all of every eval

### ISSUE THREAD

**Issue by Pietro00x** [mlabonne/llm-autoeval#32]
ARC
Average: Error: File does not exist%

HellaSwag

**Comment by mlabonne** [comment]
Can you send me your config?

**Comment by Pietro00x** [comment]
what you mean config ,i runned on runpod (with a 3090,and tried nous,openllm,and eq-bench) and all with Average: Error: File does not exist%

**Comment by Haleshot** [comment]
> Can you send me your config?

Got the same error as OP; my gist link - https://gist.github.com/Haleshot/5042ebdd0da5b1487e7e78e4a1c6dd92
_Additional Context_: Ran it through the recommended - https://github.com/CultriX-Github/llm-autoeval as referenced in your issue - https://github.com/mlabonne/llm-autoeval/issues/16; I'm running it on lightning.ai and don't have/need runpod resources.

**Comment by mlabonne** [comment]
Can you run it in debug mode to see where it fails?

**Comment by Haleshot** [comment]
> Can you run it in debug mode to see where it fails?

It works now! I switched my studio session (in [lightning.ai](https://www.lightning.ai)) to GPU -> 1 L4 instance and used the `DEBUG=TRUE` in the suggestions/commands mentioned in #16  

I'm guessing the GPU switch resolved the issue.

**Comment by mlabonne** [comment]
Excellent, yeah that might have been an issue related to the GPU or the VRAM.
