### ISSUE TITLE
Why is `mmlu` benchmark commented out?

### ISSUE THREAD

**Issue by sugatoray** [mlabonne/llm-autoeval#4]
I was going over the `runpod.sh` script and couldn't help but notice `mmlu` benchmark is commented out. I'm curious, why is that so. 

Thank you for putting this repository together @mlabonne. Learned about this from your [X-post](https://x.com/maximelabonne/status/1744640401313538366?s=20) 🚀!! 

https://github.com/mlabonne/llm-autoeval/blob/75d952ed8062123285f2733644f110e5b5743eda/runpod.sh#L86-L94

**Comment by mlabonne** [comment]
Thanks @sugatoray!

It's a little embarrassing, but I realized the MMLU doesn't work reliably after publishing this repo. Unfortunately, it looks like it's an lm-evaluation-harness issue and I can't do much about it.

I think the best workaround is simply not using vllm. I'll rename this benchmark suite "openllm-vllm" and create another one that doesn't rely on it.

**Comment by sugatoray** [comment]
@mlabonne Thank you for explaining. 

On a separate note, do you have any repositories for LLM training/finetuning with Apple Silicon? Recently I purchased a MacBook Pro Max with an M3 -- 128GB RAM and maxed out other specs. Inference is going pretty fast `ggml` formats. But I am more interested in using it for more hardcore training/experimentation purposes. Thanks anyway. :)

**Comment by mlabonne** [comment]
Not really. There are a few of them but I don't have Apple Silicon, so I
couldn't try them by myself.
